apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: aws-network
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
    version: ">=v2"
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.1'
  description: |
    Network creates AWS VPCs with subnets, routing, NAT gateways, and optional
    enterprise features. Supports IPv4, IPv6, and dual-stack configurations.
  license: Apache-2.0
  maintainer: Hops Platform Team <platform@hops.ops.com.ai>
  readme: |
    # aws-network

    AWS VPC networking configuration with support for:
    - IPv4, IPv6 (Amazon-provided or ULA), and dual-stack
    - Public and private subnets across multiple AZs
    - NAT gateways (single-AZ or highly-available)
    - Internet and Egress-Only Internet Gateways
    - VPC Flow Logs
  repository: ghcr.io/hops-ops/aws-network
  source: github.com/hops-ops/aws-network
