apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: networks.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: Network
    plural: networks
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
          Network creates AWS VPCs with subnets, routing, and optional enterprise features.
          Supports manual CIDRs or automatic IPAM-based allocation.
        required:
        - spec
        properties:
          spec:
            type: object
            description: Desired state for the Network.
            required:
            - region
            properties:
              managementPolicies:
                type: array
                description: Management operations permitted on composed resources.
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"

              # Provider Configuration
              providerConfigRef:
                type: object
                description: Reference to AWS ProviderConfig.
                properties:
                  name:
                    type: string
                    description: Name of the ProviderConfig. Defaults to "default".
                  kind:
                    type: string
                    description: Kind of the provider config reference.
                    default: ProviderConfig

              # IPAM - allocate VPC CIDR from IPAM pool, subnets calculated via cidrmath
              ipam:
                type: object
                description: |
                  Enable automatic VPC CIDR allocation from an IPAM pool.
                  Subnet CIDRs are calculated from the VPC CIDR using cidrmath.
                properties:
                  ipv4:
                    type: object
                    description: IPv4 VPC allocation from IPAM.
                    properties:
                      enabled:
                        type: boolean
                        description: Enable IPv4 CIDR allocation from IPAM.
                        default: false
                      poolId:
                        type: string
                        description: IPAM pool ID to allocate VPC CIDR from.
                      netmaskLength:
                        type: integer
                        description: Netmask length for VPC CIDR (e.g., 16 for /16).
                        default: 16
                  ipv6Ula:
                    type: object
                    description: IPv6 ULA VPC allocation from IPAM.
                    properties:
                      enabled:
                        type: boolean
                        description: Enable IPv6 ULA CIDR allocation from IPAM.
                        default: false
                      poolId:
                        type: string
                        description: IPAM pool ID to allocate VPC IPv6 CIDR from.
                      netmaskLength:
                        type: integer
                        description: Netmask length for VPC IPv6 CIDR. AWS requires /56.
                        default: 56

              # Subnet layout - used with both IPAM and manual VPC CIDR
              subnetLayout:
                type: object
                description: |
                  Subnet layout configuration. When using IPAM, subnets are
                  automatically calculated from the VPC CIDR using cidrmath.
                properties:
                  availabilityZones:
                    type: array
                    description: AZ suffixes for subnet creation (e.g., ["a", "b", "c"]).
                    items:
                      type: string
                    default:
                    - a
                    - b
                    - c
                  public:
                    type: object
                    description: Public subnet settings.
                    properties:
                      enabled:
                        type: boolean
                        description: Create public subnets.
                        default: true
                      netmaskLength:
                        type: integer
                        description: Netmask length for public subnets (e.g., 24 for /24).
                        default: 24
                  private:
                    type: object
                    description: Private subnet settings.
                    properties:
                      enabled:
                        type: boolean
                        description: Create private subnets.
                        default: true
                      netmaskLength:
                        type: integer
                        description: Netmask length for private subnets (e.g., 20 for /20).
                        default: 20

              # AWS Configuration (top-level since this is an AWS XRD)
              region:
                type: string
                description: AWS region for all managed resources.
              tags:
                type: object
                description: Extra AWS tags merged with defaults.
                x-kubernetes-preserve-unknown-fields: true

              # VPC Configuration
              vpc:
                type: object
                description: |
                  VPC configuration. CIDR can be explicit or from networkAllocations.
                properties:
                  cidr:
                    type: string
                    description: |
                      IPv4 CIDR block for the VPC (e.g., "10.1.0.0/16").
                      Optional when using networkAllocations.ipv4.
                  ipv6:
                    type: object
                    description: Optional IPv6 configuration for dual-stack.
                    properties:
                      ula:
                        type: object
                        description: ULA (Unique Local Address) IPv6 configuration.
                        properties:
                          enabled:
                            type: boolean
                            description: Enable ULA IPv6 for the VPC.
                            default: false
                          cidr:
                            type: string
                            description: |
                              ULA IPv6 CIDR block (e.g., "fd00:1234::/56").
                              Required for manual ULA configuration.
                          ipamPoolId:
                            type: string
                            description: |
                              IPAM pool ID for ULA IPv6. Required when using ULA IPv6.
                              The VPC will associate this IPv6 CIDR via IPAM.
                      amazonProvided:
                        type: object
                        description: Amazon-provided public IPv6 configuration.
                        properties:
                          enabled:
                            type: boolean
                            description: |
                              Request Amazon-provided /56 IPv6 CIDR.
                              This is public, globally routable IPv6.
                            default: false
                  forProvider:
                    type: object
                    description: Pass-through for VPC forProvider fields.
                    x-kubernetes-preserve-unknown-fields: true

              # Subnet Configuration
              subnets:
                type: array
                description: |
                  Subnet definitions. Optional when using networkAllocations.
                  When using networkAllocations, subnets are auto-generated based on
                  the allocation config (AZs, public/private settings).
                items:
                  type: object
                  required:
                  - name
                  - availabilityZone
                  properties:
                    name:
                      type: string
                      description: Subnet name (e.g., "public-a", "private-b").
                    cidr:
                      type: string
                      description: |
                        IPv4 CIDR block for the subnet.
                        Optional when using networkAllocations.ipv4.
                    availabilityZone:
                      type: string
                      description: Availability zone suffix (a, b, c) or full AZ name.
                    public:
                      type: boolean
                      description: Whether this is a public subnet (maps public IP on launch).
                      default: false
                    ipv6:
                      type: object
                      description: Optional IPv6 configuration for this subnet.
                      properties:
                        ulaCidr:
                          type: string
                          description: |
                            ULA IPv6 CIDR block for this subnet (/64).
                            Required for manual dual-stack configuration.
                        amazonProvidedCidr:
                          type: string
                          description: |
                            Amazon-provided IPv6 CIDR block for this subnet (/64).
                            Set after VPC gets Amazon-provided IPv6.

              # NAT Gateway Strategy
              nat:
                type: object
                description: NAT Gateway configuration for private subnet egress.
                properties:
                  enabled:
                    type: boolean
                    description: Enable NAT Gateways.
                    default: false
                  strategy:
                    type: string
                    description: NAT deployment strategy.
                    enum:
                    - SingleAz
                    - HighlyAvailable
                    - None
                    default: SingleAz

              # Transit Gateway
              transitGateway:
                type: object
                description: Optional Transit Gateway attachment.
                properties:
                  enabled:
                    type: boolean
                    description: Enable Transit Gateway attachment.
                    default: false
                  config:
                    type: object
                    properties:
                      tgwId:
                        type: string
                        description: Existing Transit Gateway ID (tgw-xxx).
                      routeTablePropagation:
                        type: boolean
                        description: Enable route table propagation.
                        default: true

              # Flow Logs
              flowLogs:
                type: object
                description: Optional VPC Flow Logs.
                properties:
                  enabled:
                    type: boolean
                    description: Enable VPC Flow Logs.
                    default: false
                  config:
                    type: object
                    properties:
                      destination:
                        type: string
                        description: Log destination type.
                        enum:
                        - cloudwatch
                        - s3
                        default: cloudwatch
                      logDestinationArn:
                        type: string
                        description: ARN of CloudWatch Logs group or S3 bucket.
                      iamRoleArn:
                        type: string
                        description: IAM role ARN for CloudWatch delivery.
                      trafficType:
                        type: string
                        description: Traffic type to capture.
                        enum:
                        - ALL
                        - ACCEPT
                        - REJECT
                        default: ALL

          status:
            type: object
            description: Observed state of the Network.
            properties:
              ready:
                type: boolean
              ipam:
                type: object
                description: IPAM allocation status (when using IPAM for VPC CIDR).
                properties:
                  ipv4:
                    type: object
                    description: IPv4 IPAM allocation status.
                    properties:
                      cidr:
                        type: string
                        description: Allocated VPC IPv4 CIDR from IPAM.
                  ipv6Ula:
                    type: object
                    description: IPv6 ULA IPAM allocation status.
                    properties:
                      cidr:
                        type: string
                        description: Allocated VPC IPv6 ULA CIDR from IPAM.
              network:
                type: object
                properties:
                  name:
                    type: string
                  region:
                    type: string
                  vpcId:
                    type: string
                  cidr:
                    type: object
                    properties:
                      ipv4:
                        type: string
                      ipv6Ula:
                        type: string
                      ipv6AmazonProvided:
                        type: string
                  availabilityZones:
                    type: array
                    items:
                      type: string
                  subnets:
                    type: object
                    properties:
                      public:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                            availabilityZone:
                              type: string
                            ipv4CidrBlock:
                              type: string
                            ipv6CidrBlock:
                              type: string
                      private:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                            availabilityZone:
                              type: string
                            ipv4CidrBlock:
                              type: string
                            ipv6CidrBlock:
                              type: string
                  routeTables:
                    type: object
                    properties:
                      public:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                      private:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                            availabilityZone:
                              type: string
                  natGateways:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: string
                        availabilityZone:
                          type: string
                        eipAllocationId:
                          type: string
                  internetGateway:
                    type: object
                    properties:
                      id:
                        type: string
                  egressOnlyInternetGateway:
                    type: object
                    properties:
                      id:
                        type: string
                  transitGatewayAttachment:
                    type: object
                    properties:
                      id:
                        type: string
                      state:
                        type: string
