apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: networks.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: Network
    plural: networks
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
          Network creates AWS VPCs with subnets, routing, and optional enterprise features.
          Receives explicit CIDRs from NetworkAllocation - no IPAM logic.
        required:
        - spec
        properties:
          spec:
            type: object
            description: Desired state for the Network.
            required:
            - region
            - vpc
            - subnets
            properties:
              managementPolicies:
                type: array
                description: Management operations permitted on composed resources.
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"

              # Provider Configuration
              providerConfigRef:
                type: object
                description: Reference to AWS ProviderConfig.
                properties:
                  name:
                    type: string
                    description: Name of the ProviderConfig. Defaults to "default".
                  kind:
                    type: string
                    description: Kind of the provider config reference.
                    default: ProviderConfig

              # AWS Configuration (top-level since this is an AWS XRD)
              region:
                type: string
                description: AWS region for all managed resources.
              accountId:
                type: string
                description: AWS account ID for tagging and documentation.
              tags:
                type: object
                description: Extra AWS tags merged with defaults.
                x-kubernetes-preserve-unknown-fields: true

              # VPC Configuration
              vpc:
                type: object
                description: VPC configuration with explicit CIDRs.
                required:
                - cidr
                properties:
                  cidr:
                    type: string
                    description: |
                      IPv4 CIDR block for the VPC (e.g., "10.1.0.0/16").
                      Provided by IPv4NetworkAllocation status.
                  ipv6:
                    type: object
                    description: Optional IPv6 configuration for dual-stack.
                    properties:
                      ula:
                        type: object
                        description: ULA (Unique Local Address) IPv6 configuration.
                        properties:
                          enabled:
                            type: boolean
                            description: Enable ULA IPv6 for the VPC.
                            default: false
                          cidr:
                            type: string
                            description: |
                              ULA IPv6 CIDR block (e.g., "fd00:1234::/48").
                              Provided by IPv6ULANetworkAllocation status.
                          ipamPoolId:
                            type: string
                            description: |
                              IPAM pool ID for ULA IPv6. Required when using ULA IPv6.
                              The VPC will associate this IPv6 CIDR via IPAM.
                      amazonProvided:
                        type: object
                        description: Amazon-provided public IPv6 configuration.
                        properties:
                          enabled:
                            type: boolean
                            description: |
                              Request Amazon-provided /56 IPv6 CIDR.
                              This is public, globally routable IPv6.
                            default: false
                  forProvider:
                    type: object
                    description: Pass-through for VPC forProvider fields.
                    x-kubernetes-preserve-unknown-fields: true

              # Subnet Configuration
              subnets:
                type: array
                description: |
                  Subnet definitions with explicit CIDRs.
                  Each subnet specifies its CIDR, availability zone, and type.
                items:
                  type: object
                  required:
                  - name
                  - cidr
                  - availabilityZone
                  properties:
                    name:
                      type: string
                      description: Subnet name (e.g., "public-a", "private-b").
                    cidr:
                      type: string
                      description: IPv4 CIDR block for the subnet.
                    availabilityZone:
                      type: string
                      description: Availability zone suffix (a, b, c) or full AZ name.
                    public:
                      type: boolean
                      description: Whether this is a public subnet (maps public IP on launch).
                      default: false
                    ipv6:
                      type: object
                      description: Optional IPv6 configuration for this subnet.
                      properties:
                        ulaCidr:
                          type: string
                          description: |
                            ULA IPv6 CIDR block for this subnet (/64).
                            Provided by IPv6ULANetworkAllocation status.
                        amazonProvidedCidr:
                          type: string
                          description: |
                            Amazon-provided IPv6 CIDR block for this subnet (/64).
                            Set after VPC gets Amazon-provided IPv6.

              # NAT Gateway Strategy
              nat:
                type: object
                description: NAT Gateway configuration for private subnet egress.
                properties:
                  enabled:
                    type: boolean
                    description: Enable NAT Gateways.
                    default: false
                  strategy:
                    type: string
                    description: NAT deployment strategy.
                    enum:
                    - SingleAz
                    - HighlyAvailable
                    - None
                    default: SingleAz

              # Transit Gateway
              transitGateway:
                type: object
                description: Optional Transit Gateway attachment.
                properties:
                  enabled:
                    type: boolean
                    description: Enable Transit Gateway attachment.
                    default: false
                  config:
                    type: object
                    properties:
                      tgwId:
                        type: string
                        description: Existing Transit Gateway ID (tgw-xxx).
                      routeTablePropagation:
                        type: boolean
                        description: Enable route table propagation.
                        default: true

              # Flow Logs
              flowLogs:
                type: object
                description: Optional VPC Flow Logs.
                properties:
                  enabled:
                    type: boolean
                    description: Enable VPC Flow Logs.
                    default: false
                  config:
                    type: object
                    properties:
                      destination:
                        type: string
                        description: Log destination type.
                        enum:
                        - cloudwatch
                        - s3
                        default: cloudwatch
                      logDestinationArn:
                        type: string
                        description: ARN of CloudWatch Logs group or S3 bucket.
                      iamRoleArn:
                        type: string
                        description: IAM role ARN for CloudWatch delivery.
                      trafficType:
                        type: string
                        description: Traffic type to capture.
                        enum:
                        - ALL
                        - ACCEPT
                        - REJECT
                        default: ALL

          status:
            type: object
            description: Observed state of the Network.
            properties:
              ready:
                type: boolean
              network:
                type: object
                properties:
                  name:
                    type: string
                  region:
                    type: string
                  vpcId:
                    type: string
                  cidr:
                    type: object
                    properties:
                      ipv4:
                        type: string
                      ipv6Ula:
                        type: string
                      ipv6AmazonProvided:
                        type: string
                  availabilityZones:
                    type: array
                    items:
                      type: string
                  subnets:
                    type: object
                    properties:
                      public:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                            availabilityZone:
                              type: string
                            ipv4CidrBlock:
                              type: string
                            ipv6CidrBlock:
                              type: string
                      private:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                            availabilityZone:
                              type: string
                            ipv4CidrBlock:
                              type: string
                            ipv6CidrBlock:
                              type: string
                  routeTables:
                    type: object
                    properties:
                      public:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                      private:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            id:
                              type: string
                            availabilityZone:
                              type: string
                  natGateways:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: string
                        availabilityZone:
                          type: string
                        eipAllocationId:
                          type: string
                  internetGateway:
                    type: object
                    properties:
                      id:
                        type: string
                  egressOnlyInternetGateway:
                    type: object
                    properties:
                      id:
                        type: string
                  transitGatewayAttachment:
                    type: object
                    properties:
                      id:
                        type: string
                      state:
                        type: string
