# E2E Test Configuration - Dual-stack with IPAM and per-network pools
# Mirrors the e2etest-network configuration for local testing
#
# Configuration:
# - IPv4 via IPAM poolId (PRIVATE scope pool)
# - IPv6 via IPAM poolId (PRIVATE scope ULA pool)
# - Dual-stack mode
# - Public and private subnets
# - Per-network child pools created automatically for subnet allocations
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: e2etest-network
  namespace: default
spec:
  clusterName: default
  aws:
    config:
      region: us-east-1
      tags:
        e2etest: "true"
  cidr:
    ipv4:
      ipam:
        poolId: ipam-pool-0a82c73b97dc0dabb
        # Per-network child pool created automatically
        subnetPool:
          enabled: true
          netmaskLength: 24
    ipv6:
      enabled: true
      ipam:
        poolId: ipam-pool-0decd6c5216660c74
        # Per-network child pool created automatically
        subnetPool:
          enabled: true
          netmaskLength: 64
    mode: dual-stack
  subnets:
    availabilityZones:
      - a
      - b
    types:
      - private
      - public
