# Enterprise Network - Full featured (~$150/mo)
# HA NAT + TGW + Flow Logs + Dual-Stack
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: prod-vpc
  namespace: acme-prod
spec:
  clusterName: acme-prod-cluster
  aws:
    providerConfig: acme-prod-aws
    config:
      region: us-east-1
      accountId: "123456789012"
      tags:
        environment: production
        team: platform
        cost-center: "12345"

  cidr:
    ipv4:
      ipam:
        globalPoolName: customer-prod
    ipv6:
      enabled: true
      amazonProvided: true  # Most common for enterprise - IPAM IPv6 requires poolId directly
    mode: dual-stack

  subnets:
    availabilityZones:
      - a
      - b
      - c
    netmaskLength: 19  # Larger subnets for enterprise

  nat:
    enabled: true
    strategy: HighlyAvailable  # One NAT per AZ

  transitGateway:
    enabled: true
    config:
      tgwId: tgw-abc123
      routeTablePropagation: true

  flowLogs:
    enabled: true
    config:
      destination: s3
      logDestinationArn: arn:aws:s3:::acme-flow-logs
      trafficType: ALL
