# Import Existing Resources Example
# ==================================
# This example demonstrates importing existing AWS resources using the imports object
# and per-resource managementPolicies for fine-grained control.
#
# Per-resource managementPolicies allow:
# - Full control (["*"]) on some resources while orphaning others
# - Different teams owning different resource types
# - Gradual migration from manual to Crossplane management
#
# To use for import:
# 1. Get resource IDs from AWS console or CLI
# 2. Populate the imports object with resource IDs:
#    - imports.vpc: VPC ID
#    - imports.internetGateway: IGW ID
#    - imports.egressOnlyInternetGateway: EIGW ID (if using IPv6)
#    - imports.subnets: Map of subnet keys to subnet IDs
#    - imports.routeTables: Map of route table keys to route table IDs
#    - imports.routeTableAssociations: Map of association keys to association IDs
#    - imports.natGateways: Map of AZ suffixes to NAT Gateway IDs (if using NAT)
#    - imports.eips: Map of AZ suffixes to EIP allocation IDs (if using NAT)
# 3. Set managementPolicies to orphan (exclude Delete) for safe adoption
# 4. Apply and verify resources sync correctly
# 5. Optionally update managementPolicies per resource type for full control

apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: import-example
  namespace: default
spec:
  # Default policy - orphan on delete (no Delete permission)
  managementPolicies:
  - Create
  - Observe
  - Update
  - LateInitialize

  region: us-east-1

  tags:
    Environment: production
    Team: platform

  # Import existing AWS resources
  imports:
    vpc: "vpc-0123456789abcdef0"
    internetGateway: "igw-0123456789abcdef0"
    # egressOnlyInternetGateway: "eigw-0123456789abcdef0"
    subnets:
      public-a: "subnet-0111111111111111a"
      public-b: "subnet-0222222222222222b"
      private-a: "subnet-0333333333333333a"
      private-b: "subnet-0444444444444444b"
    routeTables:
      public: "rtb-0aaaaaaaaaaaaaaa0"
      private-a: "rtb-0bbbbbbbbbbbbbbb1"
      private-b: "rtb-0ccccccccccccccc2"
    routeTableAssociations:
      public-a: "rtbassoc-0aaaa11111111111a"
      public-b: "rtbassoc-0bbbb22222222222b"
      private-a: "rtbassoc-0cccc33333333333a"
      private-b: "rtbassoc-0dddd44444444444b"
    # NAT Gateways and EIPs (if using NAT)
    # natGateways:
    #   a: "nat-0ddddddddddddddd0"
    # eips:
    #   a: "eipalloc-0eeeeeeeeeeeeeee0"

  # VPC configuration - override managementPolicies for full control after import
  vpc:
    cidr: "10.0.0.0/16"
    # Full control - Crossplane will delete if claim is deleted
    managementPolicies:
    - "*"

  # Subnet layout configuration
  subnetLayout:
    availabilityZones: ["a", "b"]
    public:
      enabled: true
      netmaskLength: 24
    private:
      enabled: true
      netmaskLength: 20
    # Subnets get full control - delete with claim
    managementPolicies:
    - "*"

  # Route tables - full control
  routeTables:
    managementPolicies:
    - "*"

  # NAT with import (if enabled)
  nat:
    enabled: false
    # managementPolicies:
    # - "*"
