# IPAM Subnet Pool Allocation
# Creates VPC with subnet CIDRs allocated from a dedicated IPAM pool
# instead of being calculated from VPC CIDR
#
# Prerequisites:
# 1. IPAM with VPC pool (globalPoolName: sandbox)
# 2. IPAM with subnet pool (globalPoolName: sandbox-subnets)
#    - Created by aws-ipam module with convention: ${globalPoolName}-subnets
#    - allocationDefaultNetmaskLength should match subnetPool.netmaskLength
#
# Benefits:
# - Stricter central control over subnet CIDR assignments
# - IPAM tracks all allocations including subnets (not just VPCs)
# - Better visibility into IP space usage at subnet granularity
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: ipam-subnets-demo
  namespace: dev
spec:
  clusterName: my-cluster
  aws:
    config:
      region: us-east-1
  cidr:
    ipv4:
      ipam:
        # VPC CIDR from this pool (e.g., gets a /16)
        globalPoolName: sandbox
        # Subnet CIDRs from sandbox-subnets pool (convention: ${globalPoolName}-subnets)
        subnetPool:
          enabled: true
          netmaskLength: 24
    mode: ipv4-only
  subnets:
    availabilityZones:
      - a
      - b
      - c
    types:
      - public
      - private
  nat:
    enabled: false
