# IPAM Subnet Pool Allocation
# Creates VPC with subnet CIDRs allocated from a dedicated IPAM pool
# instead of being calculated from VPC CIDR
#
# Prerequisites:
# 1. IPAM with VPC pool (poolId for VPC CIDR allocation)
# 2. IPAM with subnet pool (subnetPool.poolId for subnet allocations)
#    - Created by aws-ipam module with convention: ${globalPoolName}-subnets
#
# How it works:
# 1. Network creates VPCIpamPoolCidr to provision space TO the subnet pool
# 2. Once that's Ready, Network creates VPCIpamPoolCidrAllocation for each subnet
#
# Benefits:
# - Stricter central control over subnet CIDR assignments
# - IPAM tracks all allocations including subnets (not just VPCs)
# - Better visibility into IP space usage at subnet granularity
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: ipam-subnets-demo
  namespace: dev
spec:
  clusterName: my-cluster
  aws:
    config:
      region: us-east-1
  cidr:
    ipv4:
      ipam:
        # VPC CIDR from this pool (e.g., gets a /16)
        poolId: ipam-pool-0abc123def456
        # Subnet CIDRs from subnet pool
        subnetPool:
          enabled: true
          poolId: ipam-pool-0subnet123456
          netmaskLength: 24
          # Optional: explicitly set how much space to provision to the pool
          # Default is calculated as (netmaskLength - 3) to fit 8 subnets
          # poolCidrNetmaskLength: 21
    mode: ipv4-only
  subnets:
    availabilityZones:
      - a
      - b
      - c
    types:
      - public
      - private
  nat:
    enabled: false
