apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: with-allocations
  namespace: infra
spec:
  providerConfigRef:
    name: default
  region: us-east-1
  accountId: "123456789012"
  tags:
    Environment: production
    Team: platform

  # Use IPAM allocations instead of explicit CIDRs
  networkAllocations:
    ipv4:
      enabled: true
      # Regional pool ID from aws-ipam status
      regionalPoolId: ipam-pool-0123456789abcdef0
      # IPAM scope ID from aws-ipam status.ipam.privateDefaultScopeId
      scopeId: ipam-scope-0123456789abcdef0
      vpc:
        netmaskLength: 16
      subnets:
        availabilityZones:
        - a
        - b
        - c
        public:
          enabled: true
          netmaskLength: 24
        private:
          enabled: true
          netmaskLength: 20
    ipv6Ula:
      enabled: true
      # Regional ULA pool ID from aws-ipam status
      regionalPoolId: ipam-pool-0fedcba9876543210
      scopeId: ipam-scope-0fedcba9876543210
      vpc:
        netmaskLength: 48
      subnets:
        availabilityZones:
        - a
        - b
        - c
        public:
          enabled: true
          netmaskLength: 64
        private:
          enabled: true
          netmaskLength: 64

  # VPC config (cidr will come from allocations)
  vpc: {}

  # Subnets will be auto-generated from allocation config
  # Names will be: with-allocations-public-a, with-allocations-private-a, etc.

  nat:
    enabled: true
    strategy: SingleAz
